### PR TITLE
Updated to version 2023-09-07

### PR DESCRIPTION
**Pull request by olymk2**
### Summary

Updates clj-kondo to version 2023-09-07. Changelog can be found [here](https://raw.githubusercontent.com/clj-kondo/clj-kondo/v2023.09.07/CHANGELOG.md).

### Test Plan

ran clj-kondo --version to confirm the version

### Checklist

- [ ] Package was built and tested against unstable

### CODE REVIEW

**Comment by algent-al** [comment]
Please add changelogs.

**Review by algent-al — CHANGES_REQUESTED** [review]
Missing changelogs

**Comment by olymk2** [comment]
Added I think I often forget this, wonder if its worth adding to the template as a heading like summary / test plan ?

**Comment by silkeh** [comment]
LGTM, thanks!

**Pull request merged**
